# Model configuration
model:
  image_size: 224
  patch_size: 16
  num_classes: 2
  dim: 256
  depth: 6
  heads: 8
  mlp_dim: 512

# Data configuration
data:
  train_dir: "data/raw/train"
  test_dir: "data/raw/test"
  transform:
    train:
      - type: "Resize"
        size: [224, 224]
      - type: "RandomHorizontalFlip"
        p: 0.5
      - type: "RandomRotation"
        degrees: 10
      - type: "ColorJitter"
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    test:
      - type: "Resize"
        size: [224, 224]
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

# Training configuration
training:
  batch_size: 16
  num_workers: 4
  learning_rate: 0.001
  weight_decay: 0.01
  epochs: 50
  save_interval: 5

# Testing configuration
testing:
  batch_size: 16
  num_workers: 4

# Paths
paths:
  checkpoint_dir: models/weights
  log_dir: logs
  model_dir: "models"
  data_dir: "data"
  config_dir: "config"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  log_interval: 10
